// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9yzZMACt85eN_gxOFqZikB9te6BBBl2w',
    appId: '1:858448238585:web:30117330f89bf1f352cf28',
    messagingSenderId: '858448238585',
    projectId: 'spincity-98ca4',
    authDomain: 'spincity-98ca4.firebaseapp.com',
    storageBucket: 'spincity-98ca4.firebasestorage.app',
    measurementId: 'G-JGRBQE9HTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRQcD0O0ZQ37fAibQBjA9k6ONnBMMjJRw',
    appId: '1:858448238585:android:e8b026f83ace7be352cf28',
    messagingSenderId: '858448238585',
    projectId: 'spincity-98ca4',
    storageBucket: 'spincity-98ca4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0S4FDM-yJQdNJ9SS7o-8hLCeQGtPPq0',
    appId: '1:858448238585:ios:2332b8631f45248852cf28',
    messagingSenderId: '858448238585',
    projectId: 'spincity-98ca4',
    storageBucket: 'spincity-98ca4.firebasestorage.app',
    iosBundleId: 'com.example.spinCity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0S4FDM-yJQdNJ9SS7o-8hLCeQGtPPq0',
    appId: '1:858448238585:ios:2332b8631f45248852cf28',
    messagingSenderId: '858448238585',
    projectId: 'spincity-98ca4',
    storageBucket: 'spincity-98ca4.firebasestorage.app',
    iosBundleId: 'com.example.spinCity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9yzZMACt85eN_gxOFqZikB9te6BBBl2w',
    appId: '1:858448238585:web:e7e8780cb1185d3452cf28',
    messagingSenderId: '858448238585',
    projectId: 'spincity-98ca4',
    authDomain: 'spincity-98ca4.firebaseapp.com',
    storageBucket: 'spincity-98ca4.firebasestorage.app',
    measurementId: 'G-LF2QGFQCR6',
  );

}